# More advanced PDF practice

This example shows how to parse a slightly more difficult PDF using our good friend [`pdfplumber`](https://github.com/jsvine/pdfplumber).

For this exercise, we'll pull the data out of a PDF that has a fixed-width table of Colorado county-level voter registration data from April 2008. That file lives here: `../pdfs/apr08_party.pdf`.

We'll need to use a text-based strategy and [explicit vertical lines](https://github.com/jsvine/pdfplumber#table-extraction-settings) in the table extraction settings, and we'll make _liberal_ use of [list comprehensions](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions), my favorite thing in Python.

ðŸ‘‰ For more details on using list comprehensions, [see this notebook](../reference/Python%20data%20types%20and%20basic%20syntax.ipynb#List-comprehensions).

First, let's do our imports:

In [49]:
# import pdfplumber and pandas

Now let's open the PDF and dive in.

In [58]:
# open the PDF with the pdfplumber `open` function

    
    # the table settings I came up with after fiddling for a bit
    table_settings = {
        'vertical_strategy': 'text', 
        'horizontal_strategy': 'text',
        'explicit_vertical_lines': [95, 205, 245, 290]
    }
    
    # extract the table from the page

    
    # ~ lots of fiddling at this point to see what the results looked like ~
    
    # use a list comprehension to grab the headers (which are in row 4)
    # and tack on a conditional to remove blank items
    # https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions

    
    # .remove() the useless 'PREC' item from the headers

    
    # create an empty dataframe

    
    # loop over the table, slicing so that we start with row 6 and leave off some cruft at the bottom

        
        # clean up the row a little -- remove blanks and kill out commas

        
        # use zip() and dict() to marry the data and headers and then create a dictionary
        # https://docs.python.org/3/library/functions.html#func-dict
        # https://docs.python.org/3/library/functions.html#zip

        
        # append the dict to the dataframe

Where'd we land?

In [59]:
# look at df sorted on COUNTY NAME

   COUNTY NAME     REP     DEM   UNAFF   LIB  GRN NAT REF ACP GOR PLP   TOTAL
0        ADAMS   54870   69938   75221   391  130   0   1  36   0   0  200587
1      ALAMOSA    2677    3128    2426     9   12   0   0   0   0   0    8252
2     ARAPAHOE  109448   98364  105295   702  237   0   0  54   0   0  314100
3    ARCHULETA    4646    1899    2110    18   23   0   0   0   0   0    8696
4         BACA    1257    1055     518     0    1   0   0   0   0   0    2831
5         BENT     875    1070     682     2    1   0   0   1   0   0    2631
6      BOULDER   43487   76676   79252   737  862   0   0  22   0   0  201036
63  BROOMFIELD   11513    9329   12164    88   35   0   0   4   0   0   33133
7      CHAFFEE    4858    3219    3749    26   29   0   0   4   0   0   11885
8     CHEYENNE     915     230     269     2    0   0   0   1   0   0    1417
9   CLEARCREEK    2384    1955    2569    28   16   0   0   1   0   0    6953
10     CONEJOS    1768    2520     570     3    1   0   0   1   0   0    4863
11    COSTILLA     313    1701     336     1    0   0   0   1   0   0    2352
12     CROWLEY     991     571     423     0    0   0   0   0   0   0    1985
13      CUSTER    2006     608     687     7    8   0   0   0   0   0    3316
14       DELTA    8853    4159    5950    57   48   0   0   8   0   0   19075
15      DENVER   70990  167368  133835  1114  877   0   0  24   0   0  374208
16     DOLORES     549     535     357     3    2   0   0   0   0   0    1446
17     DOUGLAS   81791   33399   51308   250   91   0   0  29   0   0  166868
18       EAGLE    7982    6699   11668    54   58   0   0   2   0   0   26463
19      ELBERT    8249    2446    4426    11    8   0   0   4   0   0   15144
20      ELPASO  155039   70677  110541   703  278   0   0  53   0   0  337291
21     FREMONT   12155    6866    8568    73   36   0   0   4   0   0   27702
22    GARFIELD    9577    7039   12016    67   59   0   0   3   0   0   28761
23      GILPIN    1209    1394    2007    24   24   0   0   0   0   0    4658
24       GRAND    4793    2319    3628    19   22   0   0   0   0   0   10781
25    GUNNISON    3408    3462    4882    32   61   0   0   5   0   0   11850
26    HINSDALE     448     126     136     0    2   0   0   0   0   0     712
27    HUERFANO    1162    2566    1021    11    2   0   0   0   0   0    4762
28     JACKSON     876     164     240     6    0   0   0   0   0   0    1286
..         ...     ...     ...     ...   ...  ...  ..  ..  ..  ..  ..     ...
33     LAPLATA   11358   10453   12276   105  174   0   0   2   0   0   34368
34     LARIMER   71039   51435   69257   542  487   0   0  53   0   0  192813
35   LASANIMAS    2047    4783    1663    11    8   0   0   3   0   0    8515
36     LINCOLN    1690     605     694     6    1   0   0   0   0   0    2996
37       LOGAN    5574    2479    3246    10    2   0   0   1   0   0   11312
38        MESA   37529   18600   29508   200   94   0   0  15   0   0   85946
39     MINERAL     256     415     175     1    2   0   0   0   0   0     849
40      MOFFAT    4314    1385    2476     6    3   0   0   2   0   0    8186
41   MONTEZUMA    7059    4140    4785    26   54   0   0   0   0   0   16064
42    MONTROSE   10680    4598    7794    62   33   0   0   6   0   0   23173
43      MORGAN    6017    3111    4113    33    0   0   0   1   0   0   13275
44       OTERO    3914    4047    3238     8    3   0   0   0   0   0   11210
45       OURAY    1719     921    1034    14   12   0   0   0   0   0    3700
46        PARK    4871    2710    4371    62   15   0   0   4   0   0   12033
47    PHILLIPS    1684     587     730     6    0   0   0   0   0   0    3007
48      PITKIN    2687    4061    5578    29   49   0   0   0   0   0   12404
49     PROWERS    2743    1647    1878     7    1   0   0   0   0   0    6276
50      PUEBLO   22781   43720   28239   116   59   0   0   6   0   0   94921
51   RIOBLANCO    2530     555     979     8    4   0   0   2   0   0    4078
52   RIOGRANDE    3086    2256    1730     8    3   0   0   0   0   0    7083
53       ROUTT    5025    4615    5951    69  106   0   0   6   0   0   15772
54    SAGUACHE     862    1715    1045    35   16   0   0   0   0   0    3673
55     SANJUAN     135     162     251     4    1   0   0   1   0   0     554
56   SANMIGUEL    1095    2476    2207    40   71   0   0   0   0   0    5889
57    SEDGWICK    1041     371     453     0    0   0   0   0   0   0    1865
58      SUMMIT    5618    5128    9446    52  138   0   0   2   0   0   20384
59      TELLER    8103    3157    5409    54   16   0   0   0   0   0   16739
60  WASHINGTON    1992     438     595     2    1   0   0   3   0   0    3031
61        WELD   49535   30542   46362   295  137   0   0  78   0   0  126949
62        YUMA    2880    1140    1714     7    0   0   0   0   0   0    5741

[64 rows x 12 columns]